### ISSUE TITLE
How about the efficiency of using deque?

### ISSUE THREAD

**Issue by Sqyl** [Kosthi/minnow#1]
You know, in check0.pdf there should be a speed benchmark of the implementation, which was set at least 0.1Gb/s. I'm now using string as a buffer (though still with some stack return problems to be debugged), I wonder how fast deque can achieve and hope to make a comparison with my string achievement later.

**Comment by Sqyl** [comment]
I have finished yet. I misunderstood the usage of peek() at first, for which it could just return one <char> element from the <string> buffer. After searching and reading the pdf I realized it and changed my stream to <vector<string>> .
The judgment of capacity length and the actual stream length with vector took lots of time to write and debug, but I'm glad I finished and got an 7.08 Gbit/s in the speed test. 
Still hope to know your speed with <deque>.

**Comment by Sqyl** [comment]
I tried it for several times. It works not that steadily, as the speed oscillages in range(1.91, 7.67) Gbit/s. I guess it's up to the virual machine which may dynamicly control the performance of the stordge.

**Comment by Kosthi** [comment]
This is my deque implementation efficiency on MacBook M1. You know that machine configuration can affect efficiency, I can only say that on my MBP, the average is 30 Gbit/s, it's very fast.
<img width="585" alt="Screen Shot 2024-01-15 at 00 49 45" src="https://github.com/Kosthi/minnow/assets/30976463/01d1c497-deb6-40fd-8a82-514626049fcc">

**Comment by Kosthi** [comment]
> I have finished yet. I misunderstood the usage of peek() at first, for which it could just return one char element from the buffer. After searching and reading the pdf I realized it and changed my stream to vector<string> . The judgment of capacity length and the actual stream length with vector took lots of time to write and debug, but I'm glad I finished and got an 7.08 Gbit/s in the speed test. Still hope to know your speed with deque.

And I think that when the capacity of the vector approaches the upper limit, it requires additional overhead to expand, which is a quite time-consuming operation. You'd better use std:: string_view to reduce string copying and use deque to quickly remove header or footer elements.

**Comment by Sqyl** [comment]
Yeah, you're right. Using string_view and deque to optimize the memoryIO should be a better solution than vector.
BTW, i'm curious if MacBook can use oriented Linux, or you also used VM. I'm using VMWare with Xiaomi xxxBook21(i5-11th+3050) :)

**Comment by Kosthi** [comment]
> Yeah, you're right. Using string_view and deque to optimize the memoryIO should be a better solution than vector. BTW, i'm curious if MacBook can use oriented Linux, or you also used VM. I'm using VMWare with Xiaomi xxxBook21(i5-11th+3050) :)

I also use VM, like Parallels Desktop, and use CLion to connect virtual machines for development. I tried to compile directly on my MacBook, but failed due to missing some libraries in the Linux kernel used in the code...
